import type { PendingAuth, UserUpstreamSession } from "./types.js"

/**
 * Per-user upstream-session store for oauth2 proxies.
 *
 * Keys for upstream sessions are (userId, serverName) pairs. `userId` is the
 * verified identity from the inbound OAuth token — sessions survive transport
 * reconnects of the same user.
 *
 * Pending-auth entries are keyed by the OAuth `state` parameter generated by
 * the SDK during the authorize step; the callback route uses it to find the
 * matching provider and resume the flow.
 *
 * Implementations must be safe for concurrent use from multiple request
 * handlers on a single process. Horizontal scaling is out of scope for v1 —
 * sessions are local to the process. Production impls should persist tokens
 * (e.g. SQLite on a Fly volume) so user logins survive restarts.
 */
export interface SessionStore {
  // --- Pending auth (keyed by OAuth state) ---

  setPending(oauthState: string, auth: PendingAuth): Promise<void> | void
  getPending(oauthState: string): Promise<PendingAuth | undefined> | PendingAuth | undefined
  deletePending(oauthState: string): Promise<void> | void

  // --- Upstream sessions (keyed by userId × serverName) ---

  getSession(
    userId: string,
    serverName: string,
  ): Promise<UserUpstreamSession | undefined> | UserUpstreamSession | undefined
  setSession(userId: string, serverName: string, session: UserUpstreamSession): Promise<void> | void
  hasSession(userId: string, serverName: string): Promise<boolean> | boolean
  deleteSession(userId: string, serverName: string): Promise<void> | void
}

/**
 * Default in-memory `SessionStore`. Sessions are lost on process restart —
 * acceptable for dev and as a single-instance baseline; not suitable for
 * any deployment where restarts must not force re-login.
 */
export class InMemorySessionStore implements SessionStore {
  private readonly sessions = new Map<string, Map<string, UserUpstreamSession>>()
  private readonly pending = new Map<string, PendingAuth>()

  setPending(oauthState: string, auth: PendingAuth): void {
    this.pending.set(oauthState, auth)
  }

  getPending(oauthState: string): PendingAuth | undefined {
    const entry = this.pending.get(oauthState)
    if (!entry) return undefined
    if (Date.now() > entry.expiresAt) {
      this.pending.delete(oauthState)
      return undefined
    }
    return entry
  }

  deletePending(oauthState: string): void {
    this.pending.delete(oauthState)
  }

  getSession(userId: string, serverName: string): UserUpstreamSession | undefined {
    return this.sessions.get(userId)?.get(serverName)
  }

  setSession(userId: string, serverName: string, session: UserUpstreamSession): void {
    let forUser = this.sessions.get(userId)
    if (!forUser) {
      forUser = new Map()
      this.sessions.set(userId, forUser)
    }
    forUser.set(serverName, session)
  }

  hasSession(userId: string, serverName: string): boolean {
    return this.sessions.get(userId)?.has(serverName) ?? false
  }

  deleteSession(userId: string, serverName: string): void {
    this.sessions.get(userId)?.delete(serverName)
  }
}
